version: '3'

services:
  apache:
    image: httpd
    container_name: apache
    volumes:
      - /home/ubuntu/website:/var/www/html
    ports:
      - 80:80
  
  database:
    container_name: contsql
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kast
      MYSQL_USER: kast
      MYSQL_PASSWORD: ITF
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/sql:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: contphp
    links:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: kast
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
